/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab10;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Bilal
 */
public class frm_quest1 extends javax.swing.JFrame {

    /**
     * Creates new form frm_quest1
     */
    public frm_quest1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tbdpnl_main = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        btn_signIn = new javax.swing.JButton();
        btn_signUp = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_nameSurnameSignUp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_telephoneSignUp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_emailSignUp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_address = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        rbtn_male = new javax.swing.JRadioButton();
        rbtn_female = new javax.swing.JRadioButton();
        lbl_errorTelephone = new javax.swing.JLabel();
        btn_signUpSignUp = new javax.swing.JButton();
        btn_signUpCancel = new javax.swing.JButton();
        lbl_errorName = new javax.swing.JLabel();
        lbl_errorEmail = new javax.swing.JLabel();
        lbl_errorPassword = new javax.swing.JLabel();
        lbl_errorRepassword = new javax.swing.JLabel();
        txt_passwordSignUp = new javax.swing.JPasswordField();
        txt_repasswordSignUp = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setText("Password:");

        jLabel2.setText("E-mail:");

        btn_signIn.setText("Sign in");
        btn_signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signInActionPerformed(evt);
            }
        });

        btn_signUp.setText("Sign up");
        btn_signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(25, 25, 25)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addComponent(txt_email)))
                        .addComponent(btn_signIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_signUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btn_signIn)
                .addGap(28, 28, 28)
                .addComponent(btn_signUp)
                .addGap(43, 43, 43)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        tbdpnl_main.addTab("Sign in", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));

        jLabel3.setText("Name Surname:");

        jLabel4.setText("Telephone:");

        jLabel5.setText("E-mail:");

        jLabel6.setText("Password:");

        jLabel7.setText("Repassword:");

        jLabel8.setText("Adress:");

        txta_address.setColumns(20);
        txta_address.setRows(5);
        jScrollPane1.setViewportView(txta_address);

        jLabel9.setText("Gender:");

        buttonGroup1.add(rbtn_male);
        rbtn_male.setText("Male");

        buttonGroup1.add(rbtn_female);
        rbtn_female.setText("Female");

        lbl_errorTelephone.setForeground(new java.awt.Color(255, 0, 0));
        lbl_errorTelephone.setText(" ");

        btn_signUpSignUp.setText("Sign up");
        btn_signUpSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signUpSignUpActionPerformed(evt);
            }
        });

        btn_signUpCancel.setText("Cancel");
        btn_signUpCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signUpCancelActionPerformed(evt);
            }
        });

        lbl_errorName.setForeground(new java.awt.Color(255, 0, 0));
        lbl_errorName.setText(" ");

        lbl_errorEmail.setForeground(new java.awt.Color(255, 0, 0));
        lbl_errorEmail.setText(" ");

        lbl_errorPassword.setForeground(new java.awt.Color(255, 0, 0));
        lbl_errorPassword.setText(" ");

        lbl_errorRepassword.setForeground(new java.awt.Color(255, 0, 0));
        lbl_errorRepassword.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_errorTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtn_male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(rbtn_female))
                            .addComponent(txt_nameSurnameSignUp)
                            .addComponent(txt_telephoneSignUp)
                            .addComponent(txt_emailSignUp)
                            .addComponent(jScrollPane1)
                            .addComponent(txt_passwordSignUp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_repasswordSignUp, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_signUpSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_signUpCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_errorRepassword, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_errorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_errorName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_errorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nameSurnameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lbl_errorName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_telephoneSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbl_errorTelephone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_emailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btn_signUpSignUp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_errorEmail)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_signUpCancel)
                        .addComponent(txt_passwordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addComponent(lbl_errorPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_repasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_errorRepassword)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rbtn_male)
                    .addComponent(rbtn_female))
                .addGap(45, 45, 45))
        );

        tbdpnl_main.addTab("Sign up", jPanel2);

        getContentPane().add(tbdpnl_main);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signUpActionPerformed
        tbdpnl_main.setSelectedIndex(1);
    }//GEN-LAST:event_btn_signUpActionPerformed

    private void btn_signUpCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signUpCancelActionPerformed
        tbdpnl_main.setSelectedIndex(0);
    }//GEN-LAST:event_btn_signUpCancelActionPerformed

    private void btn_signUpSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signUpSignUpActionPerformed

        Matcher matcher;
        String x ="";
        if (txt_nameSurnameSignUp.getText().isEmpty()) {
            lbl_errorName.setText("This section couldt be empty.");
            lbl_errorName.setVisible(true);
            return;
        } else {
            matcher = Pattern.compile("^[a-zA-Z][\\w\\d]{2,}@(gmail|hotmail)(\\.com)$").matcher(txt_nameSurnameSignUp.getText());
            if (!matcher.find()) {
                lbl_errorName.setText("This section couldt be like that. Example, Fahri Muntasir.");
                lbl_errorName.setVisible(true);
                return;
            } else {
                lbl_errorName.setVisible(false);
            }
        }
        if (txt_telephoneSignUp.getText().isEmpty()) {
            lbl_errorTelephone.setText("This section couldt be empty.");
            lbl_errorTelephone.setVisible(true);
            return;
        } else {
            matcher = Pattern.compile("^\\+[1-9][0-9]?\\-\\d{10}$").matcher(txt_telephoneSignUp.getText());
            if (!matcher.find()) {
                lbl_errorTelephone.setText("This section couldt be like that.");
                lbl_errorTelephone.setVisible(true);
                return;
            } else {
                lbl_errorTelephone.setVisible(false);
            }
        }
        if (txt_emailSignUp.getText().isEmpty()) {
            lbl_errorEmail.setText("This section couldt be empty.");
            lbl_errorEmail.setVisible(true);
            return;
        } else {
            matcher = Pattern.compile("^\\w[\\w\\d]{2,}@(gmail|hotmail)(\\.com)$").matcher(txt_emailSignUp.getText());
            if (!matcher.find()) {
                lbl_errorEmail.setText("This section couldt be like that.");
                lbl_errorEmail.setVisible(true);
                return;
            } else {
                lbl_errorEmail.setVisible(false);
            }
        }
        if (txt_passwordSignUp.getText().isEmpty()) {
            lbl_errorPassword.setText("This section couldt be empty.");
            lbl_errorPassword.setVisible(true);
            return;
        } else {
            matcher = Pattern.compile("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z0-9]{5,}$").matcher(txt_passwordSignUp.getText());
            if (!matcher.find()) {
                lbl_errorPassword.setText("This section couldt be like that.");
                lbl_errorPassword.setVisible(true);
                return;
            } else {
                lbl_errorPassword.setVisible(false);
            }
        }
        if (txt_passwordSignUp.getText().isEmpty()) {
            lbl_errorPassword.setText("This section couldt be empty.");
            lbl_errorPassword.setVisible(true);
            return;
        } else {
            if (!txt_repasswordSignUp.getText().equals(txt_passwordSignUp.getText())) {
                lbl_errorPassword.setText("This section must be equal your password.");
                lbl_errorPassword.setVisible(true);
                return;
            } else {
                lbl_errorPassword.setVisible(false);
            }
        }
    }//GEN-LAST:event_btn_signUpSignUpActionPerformed

    private void btn_signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signInActionPerformed

    }//GEN-LAST:event_btn_signInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_quest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_quest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_quest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_quest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_quest1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signIn;
    private javax.swing.JButton btn_signUp;
    private javax.swing.JButton btn_signUpCancel;
    private javax.swing.JButton btn_signUpSignUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lbl_errorEmail;
    private javax.swing.JLabel lbl_errorName;
    private javax.swing.JLabel lbl_errorPassword;
    private javax.swing.JLabel lbl_errorRepassword;
    private javax.swing.JLabel lbl_errorTelephone;
    private javax.swing.JRadioButton rbtn_female;
    private javax.swing.JRadioButton rbtn_male;
    private javax.swing.JTabbedPane tbdpnl_main;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_emailSignUp;
    private javax.swing.JTextField txt_nameSurnameSignUp;
    private javax.swing.JTextField txt_password;
    private javax.swing.JPasswordField txt_passwordSignUp;
    private javax.swing.JPasswordField txt_repasswordSignUp;
    private javax.swing.JTextField txt_telephoneSignUp;
    private javax.swing.JTextArea txta_address;
    // End of variables declaration//GEN-END:variables
}
