/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjeDeneme;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Bilal
 */
public class LogIn extends javax.swing.JFrame implements Runnable {

    String nickname;
    Thread nicknameExpansion;
    boolean isExpanded;
    Color color1;
    Color color2;

    public LogIn() {
        color1 = new Color(117, 182, 255);
        color2 = new Color(101,122,248);
        initComponents();

        DegradedPanel degradedPanel = new DegradedPanel(color1, color2);

        this.setLocationRelativeTo(null);
        this.isExpanded = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_mainPanel =  new DegradedPanel(color1, color2);
        btn_play = new javax.swing.JButton();
        txt_nickname = new javax.swing.JTextField();
        lbl_nickname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        pnl_mainPanel.setBackground(new java.awt.Color(204, 204, 204));

        btn_play.setText("Play");
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });

        txt_nickname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nicknameFocusGained(evt);
            }
        });

        lbl_nickname.setText("Nickname:");

        javax.swing.GroupLayout pnl_mainPanelLayout = new javax.swing.GroupLayout(pnl_mainPanel);
        pnl_mainPanel.setLayout(pnl_mainPanelLayout);
        pnl_mainPanelLayout.setHorizontalGroup(
            pnl_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mainPanelLayout.createSequentialGroup()
                .addGroup(pnl_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_mainPanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lbl_nickname))
                    .addGroup(pnl_mainPanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(txt_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_mainPanelLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btn_play)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        pnl_mainPanelLayout.setVerticalGroup(
            pnl_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mainPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbl_nickname)
                .addGap(28, 28, 28)
                .addComponent(txt_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_play)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed

        if (!(txt_nickname.getText().isEmpty()) && confirmationOfNickname()) {
            this.nickname = txt_nickname.getText();
        } else {
            JOptionPane.showMessageDialog(this, "Please enter a nickname and be sure the length of nickname is three at least and include several words.");
            return;
        }

    }//GEN-LAST:event_btn_playActionPerformed

    public boolean confirmationOfNickname() {
        Pattern pattern = Pattern.compile("^.[a-zA-Z0-9]{2,}");
        Matcher matcher = pattern.matcher(txt_nickname.getText());
        if (matcher.find()) {
            return true;
        } else {
            return false;
        }
    }
    private void txt_nicknameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nicknameFocusGained

        if (!this.isExpanded) {
            expansionOfTextField(txt_nickname);
        } else {
            return;
        }
    }//GEN-LAST:event_txt_nicknameFocusGained
    public void expansionOfTextField(JTextField currentTextField) {
        this.nicknameExpansion = new Thread(this);
        nicknameExpansion.start();

    }

    @Override
    public void run() {
        int width = this.txt_nickname.getWidth();
        int heigth = this.txt_nickname.getHeight();
        int x = this.txt_nickname.getX();
        int y = this.txt_nickname.getY();
        int count = 0;

        while (count < 102) {
            try {
                Thread.sleep(15);
                this.txt_nickname.setSize(width + count, heigth);
                count += 2;
                this.txt_nickname.setBounds(x - (count / 2), y, width + count, heigth);
                this.repaint();
            } catch (InterruptedException ex) {
                Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.isExpanded = true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_play;
    private javax.swing.JLabel lbl_nickname;
    private javax.swing.JPanel pnl_mainPanel;
    private javax.swing.JTextField txt_nickname;
    // End of variables declaration//GEN-END:variables

}
