/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab6;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Random;
import javafx.scene.control.ToggleButton;
import javax.swing.JToggleButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author Bilal
 */
public class frm_quest1 extends javax.swing.JFrame {

    ArrayList<JToggleButton> buttons;
    JToggleButton firstSelected;
    JToggleButton secondSelected;
    int point;
    int found;

    /**
     * Creates new form frm_quest1
     */
    public frm_quest1() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panel_control = new javax.swing.JPanel();
        lbl_current = new javax.swing.JLabel();
        spn_value = new javax.swing.JSpinner();
        btn_newGame = new javax.swing.JButton();
        lbl_pointText = new javax.swing.JLabel();
        lbl_point = new javax.swing.JLabel();
        panel_game = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.GridLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(400, 300));

        panel_control.setBackground(new java.awt.Color(102, 255, 102));
        panel_control.setMinimumSize(new java.awt.Dimension(398, 100));

        lbl_current.setText("Current: ");

        spn_value.setModel(new javax.swing.SpinnerNumberModel(2, 2, 20, 2));

        btn_newGame.setText("New Game");
        btn_newGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newGameActionPerformed(evt);
            }
        });

        lbl_pointText.setText("Score:");

        lbl_point.setText("0");

        javax.swing.GroupLayout panel_controlLayout = new javax.swing.GroupLayout(panel_control);
        panel_control.setLayout(panel_controlLayout);
        panel_controlLayout.setHorizontalGroup(
            panel_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_controlLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_current)
                .addGap(18, 18, 18)
                .addComponent(spn_value, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_newGame)
                .addGap(27, 27, 27)
                .addComponent(lbl_pointText)
                .addGap(33, 33, 33)
                .addComponent(lbl_point)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        panel_controlLayout.setVerticalGroup(
            panel_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_controlLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panel_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_current)
                    .addComponent(spn_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_newGame)
                    .addComponent(lbl_pointText)
                    .addComponent(lbl_point))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(panel_control);

        panel_game.setBackground(new java.awt.Color(0, 153, 255));
        panel_game.setMinimumSize(new java.awt.Dimension(398, 193));
        jSplitPane1.setRightComponent(panel_game);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newGameActionPerformed

        buttons = new ArrayList<JToggleButton>();
        int count = (int) spn_value.getValue();

        firstSelected = null;
        secondSelected = null;
        point = 0;
        found =0;
        lbl_point.setText(point+"");
        for (int i = 0; i < count; i++) {
            JToggleButton ntbtn1 = new JToggleButton();
            ntbtn1.setText("?");
            ntbtn1.setName("ntbtn_A_" + i);
            buttons.add(ntbtn1);

            JToggleButton ntbtn2 = new JToggleButton();
            ntbtn2.setText("?");
            ntbtn2.setName("ntbtn_B_" + i);
            buttons.add(ntbtn2);

        }
        Random rand = new Random();

        while (buttons.size() > 0) {

            int index = rand.nextInt(buttons.size());
            JToggleButton stbtn = buttons.get(index);
            stbtn.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    JToggleButton tbtn = (JToggleButton) evt.getSource();
                    if ((firstSelected != null && firstSelected == tbtn) || (secondSelected != null && secondSelected == tbtn)) {
                        firstSelected.setSelected(true);
                        return;
                    }

                    if (firstSelected == null) {
                        firstSelected = tbtn;
                        String nameFirst = tbtn.getName();
                        int firstNumber = getNumber(nameFirst);
                        firstSelected.setText(Integer.toString(firstNumber));

                    } else if (secondSelected == null) {
                        secondSelected = tbtn;
                        String secondName = tbtn.getName();
                        int secondNumber = getNumber(secondName);
                        secondSelected.setText(secondNumber + "");

                        String nameFirst = firstSelected.getName();
                        int firstNumber = getNumber(nameFirst);

                        if (firstNumber == secondNumber) {
                            point += 10;
                            firstSelected.setEnabled(false);
                            secondSelected.setEnabled(false);
                            firstSelected = null;
                            secondSelected = null;

                            found++;
                            if (found == count) {

                                panel_game.removeAll();
                                SwingUtilities.invokeLater(new Runnable() {
                                    public void run() {
                                        panel_game.repaint();
                                    }
                                });
                            }
                        } else {
                            point -= 5;
                        }
                        lbl_point.setText(point + "");
                    } else {
                        firstSelected.setSelected(false);
                        secondSelected.setSelected(false);
                        firstSelected.setText("?");
                        secondSelected.setText("?");
                        firstSelected = null;
                        secondSelected = null;

                        firstSelected = tbtn;
                        String nameFirst = tbtn.getName();
                        int firstNumber = getNumber(nameFirst);
                        firstSelected.setText(Integer.toString(firstNumber));
                    }

                }
            });

            panel_game.add(stbtn);
            buttons.remove(index);

        }
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                panel_game.revalidate();
            }
        });
    }//GEN-LAST:event_btn_newGameActionPerformed

    public int getNumber(String value) {
        int number = -1;
        if (value.contains("ntbtn_A")) {
            number = Integer.parseInt(value.replace("ntbtn_A_", ""));
        } else {
            number = Integer.parseInt(value.replace("ntbtn_B_", ""));
        }
        return number;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_quest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_quest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_quest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_quest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_quest1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_newGame;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lbl_current;
    private javax.swing.JLabel lbl_point;
    private javax.swing.JLabel lbl_pointText;
    private javax.swing.JPanel panel_control;
    private javax.swing.JPanel panel_game;
    private javax.swing.JSpinner spn_value;
    // End of variables declaration//GEN-END:variables
}
