/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SomeQuestions;

import java.awt.Color;
import javax.swing.ButtonGroup;

/**
 *
 * @author Bilal
 */
public class frm_question8 extends javax.swing.JFrame {

    /**
     * Creates new form frm_question8
     */
    public frm_question8() {
        initComponents();
        grupla();
    }

    public void grupla() {
        group_1.add(rbtn_1);
        group_1.add(rbtn_2);
        group_1.add(rbtn_3);
        group_2.add(rbtn_4);
        group_2.add(rbtn_5);
        group_2.add(rbtn_6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        pan_1 = new javax.swing.JPanel();
        rbtn_1 = new javax.swing.JRadioButton();
        rbtn_2 = new javax.swing.JRadioButton();
        rbtn_3 = new javax.swing.JRadioButton();
        pan_2 = new javax.swing.JPanel();
        rbtn_4 = new javax.swing.JRadioButton();
        rbtn_5 = new javax.swing.JRadioButton();
        rbtn_6 = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbtn_1.setText("red");
        rbtn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_1ActionPerformed(evt);
            }
        });

        rbtn_2.setText("green");
        rbtn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_2ActionPerformed(evt);
            }
        });

        rbtn_3.setText("blue");
        rbtn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_1Layout = new javax.swing.GroupLayout(pan_1);
        pan_1.setLayout(pan_1Layout);
        pan_1Layout.setHorizontalGroup(
            pan_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_1Layout.createSequentialGroup()
                .addGroup(pan_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtn_3)
                    .addComponent(rbtn_2)
                    .addComponent(rbtn_1))
                .addGap(0, 33, Short.MAX_VALUE))
        );
        pan_1Layout.setVerticalGroup(
            pan_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(rbtn_1)
                .addGap(27, 27, 27)
                .addComponent(rbtn_2)
                .addGap(33, 33, 33)
                .addComponent(rbtn_3)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        rbtn_4.setText("red");
        rbtn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_4ActionPerformed(evt);
            }
        });

        rbtn_5.setText("green");
        rbtn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_5ActionPerformed(evt);
            }
        });

        rbtn_6.setText("blue");
        rbtn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_2Layout = new javax.swing.GroupLayout(pan_2);
        pan_2.setLayout(pan_2Layout);
        pan_2Layout.setHorizontalGroup(
            pan_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_2Layout.createSequentialGroup()
                .addGroup(pan_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtn_4)
                    .addComponent(rbtn_5)
                    .addComponent(rbtn_6))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        pan_2Layout.setVerticalGroup(
            pan_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(rbtn_4)
                .addGap(28, 28, 28)
                .addComponent(rbtn_5)
                .addGap(29, 29, 29)
                .addComponent(rbtn_6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pan_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pan_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pan_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pan_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_1ActionPerformed
        pan_1.setBackground(Color.red);

    }//GEN-LAST:event_rbtn_1ActionPerformed

    private void rbtn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_4ActionPerformed
        pan_2.setBackground(Color.red);
    }//GEN-LAST:event_rbtn_4ActionPerformed

    private void rbtn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_2ActionPerformed
        pan_1.setBackground(Color.green);
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_2ActionPerformed

    private void rbtn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_5ActionPerformed
        pan_2.setBackground(Color.green);
    }//GEN-LAST:event_rbtn_5ActionPerformed

    private void rbtn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_3ActionPerformed
        pan_1.setBackground(Color.blue);
    }//GEN-LAST:event_rbtn_3ActionPerformed

    private void rbtn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_6ActionPerformed
        pan_2.setBackground(Color.blue);
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_question8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_question8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_question8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_question8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new frm_question8().setVisible(true);

            }
        });
    }

    ButtonGroup group_1 = new ButtonGroup();
    ButtonGroup group_2 = new ButtonGroup();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pan_1;
    private javax.swing.JPanel pan_2;
    private javax.swing.JRadioButton rbtn_1;
    private javax.swing.JRadioButton rbtn_2;
    private javax.swing.JRadioButton rbtn_3;
    private javax.swing.JRadioButton rbtn_4;
    private javax.swing.JRadioButton rbtn_5;
    private javax.swing.JRadioButton rbtn_6;
    // End of variables declaration//GEN-END:variables
}
