/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab5;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Bilal
 */
public class frm_quest2 extends javax.swing.JFrame {

    DefaultListModel listImageModel;
    DefaultListModel listLogModel;
    Map<String,String> imageMap;
    
    public frm_quest2() {
        initComponents();

        this.listImageModel = new DefaultListModel();
        list_image.setModel(listImageModel);
        this.listLogModel = new DefaultListModel();
        list_log.setModel(listLogModel);
        
        System.out.println(this.getClass().getClassLoader().getResource(""));
        
        String imageFolderPath = this.getClass().getClassLoader().getResource("images").getFile();
        File file = new File(imageFolderPath);
        File[] files = file.listFiles();
        
        Log("Resimler okunuyor");
        imageMap= new HashMap<>();
        for(File siradaki: files){
            listImageModel.addElement(siradaki.getName());
            imageMap.put(siradaki.getName(), siradaki.getAbsolutePath());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_image = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_image = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_log = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setDividerSize(10);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane2.setDividerLocation(200);
        jSplitPane2.setDividerSize(10);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());
        jPanel1.add(lbl_image, new java.awt.GridBagConstraints());

        jSplitPane2.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Images"));
        jPanel2.setLayout(new java.awt.GridLayout());

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 255));

        list_image.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_imageValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_image);

        jPanel2.add(jScrollPane1);

        jSplitPane2.setLeftComponent(jPanel2);

        jSplitPane1.setTopComponent(jSplitPane2);

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Logs"));
        jPanel3.setLayout(new java.awt.GridLayout());

        jScrollPane2.setBorder(null);

        jScrollPane2.setViewportView(list_log);

        jPanel3.add(jScrollPane2);

        jSplitPane1.setRightComponent(jPanel3);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void list_imageValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_imageValueChanged
        Log("Resim degistirilmekte...");
        String imageName = list_image.getSelectedValue();
        String imagePath = imageMap.get(imageName);
        ImageIcon image = new ImageIcon(imagePath);
        lbl_image.setIcon(image);
        Log("Resim gosteriliyor");
    }//GEN-LAST:event_list_imageValueChanged

    public void Log(String msg){
        listLogModel.addElement(msg);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_quest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_quest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_quest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_quest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_quest2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JList<String> list_image;
    private javax.swing.JList<String> list_log;
    // End of variables declaration//GEN-END:variables
}
