/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab4;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Bilal
 */
public class frm_quest1_2_3 extends javax.swing.JFrame {
    
    private ArrayList<Person> personList = new ArrayList<Person>();

    /**
     * Creates new form frm_quest1
     */
    public frm_quest1_2_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_1 = new javax.swing.JLabel();
        txt_1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lbl_2 = new javax.swing.JLabel();
        txt_2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lbl_3 = new javax.swing.JLabel();
        txtp_1 = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        txtf_1 = new javax.swing.JLabel();
        txtf_phone = new javax.swing.JFormattedTextField();
        jPanel8 = new javax.swing.JPanel();
        rbtn_male = new javax.swing.JRadioButton();
        rbtn_female = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        rbtn_smoke = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btn_apply = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 420));
        setPreferredSize(new java.awt.Dimension(420, 420));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 420));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 420));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setMaximumSize(new java.awt.Dimension(3000, 1000));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(420, 60));
        jPanel3.setLayout(new java.awt.FlowLayout(1, 5, 23));

        lbl_1.setText("Mail:");
        jPanel3.add(lbl_1);

        txt_1.setText("jTextField1");
        jPanel3.add(txt_1);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setForeground(new java.awt.Color(255, 102, 102));
        jPanel4.setMaximumSize(new java.awt.Dimension(3000, 1000));
        jPanel4.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel4.setName(""); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(420, 60));
        jPanel4.setLayout(new java.awt.FlowLayout(1, 5, 23));

        lbl_2.setText("Name Surname");
        jPanel4.add(lbl_2);

        txt_2.setText("jTextField2");
        jPanel4.add(txt_2);

        jPanel1.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(51, 51, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(3000, 1000));
        jPanel5.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel5.setName(""); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(420, 60));
        jPanel5.setLayout(new java.awt.FlowLayout(1, 5, 23));

        lbl_3.setText("Password");
        jPanel5.add(lbl_3);

        txtp_1.setText("jPasswordField1");
        jPanel5.add(txtp_1);

        jPanel1.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(51, 255, 51));
        jPanel6.setMaximumSize(new java.awt.Dimension(3000, 1000));
        jPanel6.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel6.setName(""); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(420, 60));
        jPanel6.setLayout(new java.awt.FlowLayout(1, 5, 23));

        txtf_1.setText("Phone");
        jPanel6.add(txtf_1);

        try {
            txtf_phone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("( 0###)-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(txtf_phone);

        jPanel1.add(jPanel6);

        jPanel8.setBackground(new java.awt.Color(51, 255, 255));
        jPanel8.setMaximumSize(new java.awt.Dimension(3000, 1000));
        jPanel8.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel8.setName(""); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(420, 60));
        jPanel8.setLayout(new java.awt.FlowLayout(1, 5, 23));

        buttonGroup1.add(rbtn_male);
        rbtn_male.setText("Male");
        jPanel8.add(rbtn_male);

        buttonGroup1.add(rbtn_female);
        rbtn_female.setText("Female");
        jPanel8.add(rbtn_female);

        jPanel1.add(jPanel8);

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));
        jPanel7.setMaximumSize(new java.awt.Dimension(3000, 1000));
        jPanel7.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel7.setName(""); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(420, 60));
        jPanel7.setLayout(new java.awt.FlowLayout(1, 5, 23));

        rbtn_smoke.setText("Smoker");
        jPanel7.add(rbtn_smoke);

        jPanel1.add(jPanel7);

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setMinimumSize(new java.awt.Dimension(120, 420));
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 420));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btn_apply.setText("Apply");
        btn_apply.setMaximumSize(new java.awt.Dimension(200, 200));
        btn_apply.setMinimumSize(new java.awt.Dimension(100, 50));
        btn_apply.setPreferredSize(new java.awt.Dimension(90, 90));
        btn_apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_applyActionPerformed(evt);
            }
        });
        jPanel2.add(btn_apply, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean Register() {
        
        boolean current = false;
        String mail;
        String name;
        String phone;
        String password;
        boolean isSmoker;
        char gender;
        
        if (txt_1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "lutfen mail alanini doldur");
            return current;
        }
        if (txt_2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "lutfen isim alanini doldur");
            return current;
        }
        if (txtf_phone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "lutfen telefonunu alanini doldur");
            return current;
            
        }
        if (txtp_1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "lutfen parola alanini doldur");
            return current;
            
        }
        if (!(rbtn_female.isSelected() || rbtn_male.isSelected())) {
            JOptionPane.showMessageDialog(this, "lutfen cinsiyet alanini doldur");
            return current;
            
        }
        
        if (!txtf_phone.isValid()) {
            JOptionPane.showMessageDialog(this, "Telefon numarasini dogru giriniz");
            return current;
            
        }
        
        mail = txt_1.getText();
        name = txt_2.getText();
        phone = txtf_phone.getText();
        password = txtp_1.getPassword().toString();
        if (rbtn_female.isSelected()) {
            gender = 'F';
        } else {
            gender = 'M';
        }
        isSmoker = rbtn_smoke.isSelected();
        
        String password3 = txtp_1.getText();
        String password2 = JOptionPane.showInputDialog(rootPane, "Sifreyi tekrar giriniz", "sifre yeniden girmewk", JOptionPane.INFORMATION_MESSAGE);
        if (password2 ==null ||!password2.equals(password3)) {
            JOptionPane.showMessageDialog(rootPane, "Sifreyi yanlıs girdiniz");
            return current;
            
        }
        int value = JOptionPane.showConfirmDialog(this, "Gercekten kaydolmak istiyor musun?", "kontrol", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (value == JOptionPane.NO_OPTION) {
            return current;
            
        }
        
        Person person = new Person();
        current = true;
        person.gender = gender;
        person.name = name;
        person.isSmoker = isSmoker;
        person.mail = mail;
        person.password = password;
        person.phone = phone;
        
        this.personList.add(person);
        return current;
    }

    private void btn_applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_applyActionPerformed
        
        Register();
    }//GEN-LAST:event_btn_applyActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        int value = JOptionPane.showConfirmDialog(rootPane, "Cikmadan once kaydetmek ister misiniz?", "Dikkat", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        if (value == JOptionPane.YES_OPTION) {
            
            if (Register()) {
                this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            } else {
                this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            }
        } else if (value == JOptionPane.NO_OPTION) {
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        } else {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_quest1_2_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_quest1_2_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_quest1_2_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_quest1_2_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_quest1_2_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apply;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JRadioButton rbtn_female;
    private javax.swing.JRadioButton rbtn_male;
    private javax.swing.JRadioButton rbtn_smoke;
    private javax.swing.JTextField txt_1;
    private javax.swing.JTextField txt_2;
    private javax.swing.JLabel txtf_1;
    private javax.swing.JFormattedTextField txtf_phone;
    private javax.swing.JPasswordField txtp_1;
    // End of variables declaration//GEN-END:variables
}
