/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab4;

import java.awt.event.MouseEvent;
import javax.swing.SwingUtilities;

/**
 *
 * @author Bilal
 */
public class frm_quest4 extends javax.swing.JFrame {

    private String text;
    /**
     * Creates new form frm_quest4
     */
    public frm_quest4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup_menu = new javax.swing.JPopupMenu();
        mitem_popupCut = new javax.swing.JMenuItem();
        mitem_popupCopy = new javax.swing.JMenuItem();
        mitem_popupPaste = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitem_fileSave = new javax.swing.JMenuItem();
        mitem_fileClose = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitem_editCut = new javax.swing.JMenuItem();
        mitem_editPaste = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        mitem_popupCut.setText("Cut");
        mitem_popupCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_popupCutActionPerformed(evt);
            }
        });
        popup_menu.add(mitem_popupCut);

        mitem_popupCopy.setText("Copy");
        mitem_popupCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_popupCopyActionPerformed(evt);
            }
        });
        popup_menu.add(mitem_popupCopy);

        mitem_popupPaste.setText("Paste");
        mitem_popupPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_popupPasteActionPerformed(evt);
            }
        });
        popup_menu.add(mitem_popupPaste);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txta_1.setColumns(20);
        txta_1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txta_1.setLineWrap(true);
        txta_1.setRows(5);
        txta_1.setText("Velelelee lalalala lolololo");
        txta_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txta_1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txta_1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txta_1);

        jMenu1.setText("File");

        mitem_fileSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitem_fileSave.setText("Save");
        mitem_fileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_fileSaveActionPerformed(evt);
            }
        });
        jMenu1.add(mitem_fileSave);

        mitem_fileClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitem_fileClose.setText("Close");
        mitem_fileClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_fileCloseActionPerformed(evt);
            }
        });
        jMenu1.add(mitem_fileClose);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        mitem_editCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitem_editCut.setText("Cut");
        mitem_editCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_popupCutActionPerformed(evt);
            }
        });
        jMenu2.add(mitem_editCut);

        mitem_editPaste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitem_editPaste.setText("Copy");
        mitem_editPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_popupCopyActionPerformed(evt);
            }
        });
        jMenu2.add(mitem_editPaste);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Paste");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_popupPasteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitem_fileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_fileSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mitem_fileSaveActionPerformed

    private void mitem_fileCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_fileCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_mitem_fileCloseActionPerformed

    private void txta_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txta_1MousePressed
       if(SwingUtilities.isRightMouseButton(evt)){
            showPopup(evt);
        }    }//GEN-LAST:event_txta_1MousePressed

    private void txta_1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txta_1MouseReleased
        if(SwingUtilities.isRightMouseButton(evt)){
            showPopup(evt);
        }

    }//GEN-LAST:event_txta_1MouseReleased

    private void mitem_popupCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_popupCutActionPerformed
        this.text= txta_1.getSelectedText();
        txta_1.replaceSelection("");
    }//GEN-LAST:event_mitem_popupCutActionPerformed

    private void mitem_popupCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_popupCopyActionPerformed
        this.text= txta_1.getSelectedText();
    }//GEN-LAST:event_mitem_popupCopyActionPerformed

    private void mitem_popupPasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_popupPasteActionPerformed
        txta_1.insert(text, txta_1.getSelectionStart());

    }//GEN-LAST:event_mitem_popupPasteActionPerformed
    private void showPopup(MouseEvent evt){
        if(evt.isPopupTrigger()){
            popup_menu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_quest4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_quest4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_quest4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_quest4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_quest4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mitem_editCut;
    private javax.swing.JMenuItem mitem_editPaste;
    private javax.swing.JMenuItem mitem_fileClose;
    private javax.swing.JMenuItem mitem_fileSave;
    private javax.swing.JMenuItem mitem_popupCopy;
    private javax.swing.JMenuItem mitem_popupCut;
    private javax.swing.JMenuItem mitem_popupPaste;
    private javax.swing.JPopupMenu popup_menu;
    private javax.swing.JTextArea txta_1;
    // End of variables declaration//GEN-END:variables
}
